name: CI

on: [push, pull_request]  # ← isso é essencial!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Rodar testes (exemplo)
        run: |
          echo "Aqui você pode rodar seus testes"
